# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eca47f5cde301ada9e7dde189b82b96daa4f4134bde8fbf92fae78c70fb506f580efb4e117415a494e637d7525ff726b53b71bf0abcf5ceee68a6f554d00e6f3

test:
  secret_key_base: 9287292fa11321c00038acb2a3a2b03eec6eccad0da7e1afd08daed92eebdf3e60cac227c7f20c5e773591f65ac7a009d5ebeab014bae5ed9d0ea52afda0cdb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
